{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"failTest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.apple.swift-distributed-actors\/documentation\/DistributedActorsTestKit\/CallSiteError","preciseIdentifier":"s:24DistributedActorsTestKit13CallSiteErrorV","text":"CallSiteError"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/distributedactorstestkit\/callsiteinfo\/error(_:failtest:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.apple.swift-distributed-actors\/documentation\/DistributedActorsTestKit\/CallSiteInfo\/error(_:failTest:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns an Error that should be thrown by the called."},{"type":"text","text":" "},{"type":"text","text":"The failure contains the passed in message as well as source location of the call site, for easier locating of the issue."}],"kind":"symbol","metadata":{"role":"symbol","title":"error(_:failTest:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"failTest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CallSiteError","preciseIdentifier":"s:24DistributedActorsTestKit13CallSiteErrorV"}],"symbolKind":"method","externalID":"s:24DistributedActorsTestKit12CallSiteInfoV5error_04failC0AA0eF5ErrorVSS_SbtF","extendedModule":"DistributedActorsTestKit","modules":[{"name":"DistributedActorsTestKit"}]},"hierarchy":{"paths":[["doc:\/\/com.apple.swift-distributed-actors\/documentation\/DistributedActorsTestKit","doc:\/\/com.apple.swift-distributed-actors\/documentation\/DistributedActorsTestKit\/CallSiteInfo"]]},"references":{"doc://com.apple.swift-distributed-actors/documentation/DistributedActorsTestKit":{"role":"collection","title":"DistributedActorsTestKit","abstract":[],"identifier":"doc:\/\/com.apple.swift-distributed-actors\/documentation\/DistributedActorsTestKit","kind":"symbol","type":"topic","url":"\/documentation\/distributedactorstestkit"},"doc://com.apple.swift-distributed-actors/documentation/DistributedActorsTestKit/CallSiteInfo/error(_:failTest:)":{"role":"symbol","title":"error(_:failTest:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"failTest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CallSiteError","preciseIdentifier":"s:24DistributedActorsTestKit13CallSiteErrorV"}],"abstract":[{"type":"text","text":"Returns an Error that should be thrown by the called."},{"type":"text","text":" "},{"type":"text","text":"The failure contains the passed in message as well as source location of the call site, for easier locating of the issue."}],"identifier":"doc:\/\/com.apple.swift-distributed-actors\/documentation\/DistributedActorsTestKit\/CallSiteInfo\/error(_:failTest:)","kind":"symbol","type":"topic","url":"\/documentation\/distributedactorstestkit\/callsiteinfo\/error(_:failtest:)"},"doc://com.apple.swift-distributed-actors/documentation/DistributedActorsTestKit/CallSiteInfo":{"role":"symbol","title":"CallSiteInfo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallSiteInfo"}],"abstract":[],"identifier":"doc:\/\/com.apple.swift-distributed-actors\/documentation\/DistributedActorsTestKit\/CallSiteInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallSiteInfo"}],"url":"\/documentation\/distributedactorstestkit\/callsiteinfo"},"doc://com.apple.swift-distributed-actors/documentation/DistributedActorsTestKit/CallSiteError":{"role":"symbol","title":"CallSiteError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallSiteError"}],"abstract":[{"type":"text","text":"An error type with additional "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.apple.swift-distributed-actors\/documentation\/DistributedActorsTestKit\/CallSiteInfo"},{"type":"text","text":" which is able to pretty print failures."},{"type":"text","text":" "},{"type":"text","text":"It is useful for printing complex failures on the command line and is usually thrown by "},{"type":"codeVoice","code":"should"},{"type":"text","text":" matchers."}],"identifier":"doc:\/\/com.apple.swift-distributed-actors\/documentation\/DistributedActorsTestKit\/CallSiteError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallSiteError"}],"url":"\/documentation\/distributedactorstestkit\/callsiteerror"}}}